---
apiVersion: v1
kind: Namespace
metadata:
  name: test
spec:
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf-web
  namespace: test
data:
  nginx.conf: |
    server {
      listen       PORT;
      listen  [::]:PORT;
      server_name  localhost;

      location / {
          root   /usr/share/nginx/html;
          index  index.html index.htm;
      }

      error_page   500 502 503 504  /50x.html;
      location = /50x.html {
          root   /usr/share/nginx/html;
      }
    }
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-web
  namespace: test
spec:
  containers:
  - name: nginx-web
    image: nginx:1.22
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - mountPath: /etc/nginx/nginx.conf.d/
      readOnly: true
      name: nginx-conf-web
    - mountPath: /var/log/nginx
      name: nginx-logs
    ports:
    - name: nginx-web-port
      containerPort: PORT
      protocol: TCP
  volumes:
  - name: nginx-conf-web
    configMap:
      name: nginx-conf-web
      items:
      - key: nginx.conf
        path: default.conf
  - name: nginx-logs
    emptyDir: {}
---