---
apiVersion: v1
kind: Namespace
metadata:
  name: pre
spec:
---
apiVersion: v1
kind: Namespace
metadata:
  name: pro
spec:
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx
  namespace: pre
  labels:
    app.kubernetes.io/name: nginx-conf
    app.kubernetes.io/part-of: learning-configmap
    app.kubernetes.io/component: conf
data:
  nginx.conf: |
    server {
      listen       80;
      listen  [::]:80;
      server_name  localhost;

      location / {
          root   /usr/share/nginx/html;
          index  index.html index.htm;
      }

      error_page   500 502 503 504  /50x.html;
      location = /50x.html {
          root   /usr/share/nginx/html;
      }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx
  namespace: pro
  labels:
    app.kubernetes.io/name: nginx-conf
    app.kubernetes.io/part-of: learning-configmap
    app.kubernetes.io/component: conf
data:
  nginx.conf: |
    server {
      listen       90;
      listen  [::]:90;
      server_name  localhost;

      location / {
          root   /usr/share/nginx/html;
          index  index.html index.htm;
      }

      error_page   500 502 503 504  /50x.html;
      location = /50x.html {
          root   /usr/share/nginx/html;
      }
    }
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: pre
  labels:
    app.kubernetes.io/name: nginx-svc
    app.kubernetes.io/part-of: learning-configmap
    app.kubernetes.io/component: svc
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: nginx-server
    app.kubernetes.io/part-of: learning-configmap
  ports:
  - name: web 
    port: 80
    targetPort: 80
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: pro
  labels:
    app.kubernetes.io/name: nginx-svc
    app.kubernetes.io/part-of: learning-configmap
    app.kubernetes.io/component: svc
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: nginx-server
    app.kubernetes.io/part-of: learning-configmap
  ports:
  - name: web
    port: 90
    targetPort: 90
    protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: NS
  labels:
    app.kubernetes.io/name: nginx-server
    app.kubernetes.io/part-of: learning-configmap
    app.kubernetes.io/component: server
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx-server
      app.kubernetes.io/part-of: learning-configmap
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx-server
        app.kubernetes.io/part-of: learning-configmap
    spec:
      restartPolicy: Always
      containers:
      - name: nginx
        image: nginx:1.22
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/nginx.conf.d/
          readOnly: true
        - name: nginx-logs
          mountPath: /var/log/nginx
      volumes:
      - name: nginx-conf
        configMap:
          name: nginx
          items:
          - key: nginx.conf
            path: nginx.conf
      - name: nginx-logs
        emptyDir: {}
