---
apiVersion: v1
kind: Namespace
metadata:
  name: test
spec:
---
apiVersion: v1
kind: Service
metadata:
  name: tcp-liveness-probe
  namespace: test
  labels:
    app.kubernetes.io/name: tcp
    app.kubernetes.io/part-of: liveness
    app.kubernetes.io/component: probe
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: tcp
    app.kubernetes.io/part-of: liveness
  ports:
  - name: tcp
    port: 8080
    targetPort: 8080
    protocol: TCP
---
apiVersion: v1
kind: Pod
metadata:
  name: tcp-liveness-probe
  namespace: test
  labels:
    app.kubernetes.io/name: tcp
    app.kubernetes.io/part-of: liveness
    app.kubernetes.io/component: probe
spec:
  restartPolicy: OnFailure
  containers:
  - name: tcp
    image: registry.k8s.io/goproxy:0.1
    imagePullPolicy: IfNotPresent
    ports:
    - name: tcp
      containerPort: 8080
      protocol: TCP
    livenessProbe:
      tcpSocket:
        port: 8080
      initialDelaySeconds: 5
      timeoutSeconds: 2
      periodSeconds: 20
      successThreshold: 1
      failureThreshold: 3
