---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
spec:
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitoring
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: observability
    app.kubernetes.io/component: observator
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: observability
  ports:
  - port: 3000
    targetPort: grafana
    nodePort: 30001
    protocol: TCP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
  namespace: monitoring
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: observability
    app.kubernetes.io/component: observator
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: monitoring
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: observability
    app.kubernetes.io/component: observator
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: grafana
      app.kubernetes.io/part-of: observability
  template:
    metadata:
      labels:
        app.kubernetes.io/name: grafana
        app.kubernetes.io/part-of: observability
        app.kubernetes.io/component: observator
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:9.1.0
        imagePullPolicy: IfNotPresent
        ports:
        - name: grafana
          containerPort: 3000
          protocol: TCP
        livenessProbe:
          tcpSocket:
            port: grafana
          initialDelaySeconds: 5
          timeoutSeconds: 5
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3 
        readinessProbe:
          httpGet:
            scheme: HTTP
            path: /robots.txt
            port: grafana
          initialDelaySeconds: 5
          timeoutSeconds: 5 
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        resources:
          requests:
            cpu: 250m
            memory: 750Mi
          limits:
            cpu: 400m
            memory: 900Mi
        volumeMounts:
        - mountPath: /var/lib/grafana
          name: grafana-pv
      volumes:
      - name: grafana-pv
        persistentVolumeClaim:
          claimName: grafana-pvc