apiVersion: v1
kind: Service
metadata:
  name: traefik-prometheus
  namespace: kube-system
  labels:
    app.kubernetes.io/name: traefik-prometheus
    app.kubernetes.io/instance: traefik
    app.kubernetes.io/part-of: observability
spec:
  selector:
    app.kubernetes.io/name: traefik
    app.kubernetes.io/instance: traefik
  ports:
  - name: metrics
    port: 9100
    targetPort: 9100
    protocol: TCP
  type: ClusterIP