---
apiVersion: v1
kind: Namespace
metadata:
  name: test
spec:
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-web
  namespace: test
  labels:
    app.kubernetes.io/name: nginx
    app.kubernetes.io/part-of: learning
    app.kubernetes.io/component: web
    app.kubernetes.io/version: "0.0.1"
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx
      app.kubernetes.io/component: web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx
        app.kubernetes.io/part-of: learning
        app.kubernetes.io/component: web
        app.kubernetes.io/version: "0.0.1"
    spec:
      restartPolicy: Always
      containers:
      - name: nginx
        image: nginx:1.22
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        livenessProbe:
          httpGet:
            scheme: HTTP
            port: 80
            path: /
            httpHeaders:
            - name: Accept
              value: text/html
          initialDelaySeconds: 5 # default is 0
          periodSeconds: 30 # default is 10
          timeoutSeconds: 5 # default is 1
          successThreshold: 1 # default is 1
          failureThreshold: 3 # default is 3
        readinessProbe:
          httpGet:
            path: /
            port: 80
            httpHeaders:
            - name: Accept
              value: text/html
          initialDelaySeconds: 5
          periodSeconds: 30
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-web
  namespace: test
  labels:
    app.kubernetes.io/name: nginx
    app.kubernetes.io/part-of: learning
    app.kubernetes.io/version: "0.0.1"
spec:
  type: NodePort
  ports:
  - name: http
    port: 8080
    targetPort: 80
    protocol: TCP
  selector:
    app.kubernetes.io/name: nginx
    app.kubernetes.io/component: web
