---
apiVersion: v1
kind: Namespace
metadata:
  name: test
spec:
---
apiVersion: v1
kind: Service
metadata:
  name: server-livenesss-get-http
  namespace: test
  labels:
    app.kubernetes.io/name: server
    app.kubernetes.io/part-of: liveness
    app.kubernetes.io/component: web
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: server
    app.kubernetes.io/part-of: liveness
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-liveness-get-http
  namespace: test
  labels:
    app.kubernetes.io/name: server
    app.kubernetes.io/part-of: liveness
    app.kubernetes.io/component: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: server
      app.kubernetes.io/part-of: liveness
  template:
    metadata:
      labels:
        app.kubernetes.io/name: server
        app.kubernetes.io/part-of: liveness
        app.kubernetes.io/component: web
    spec:
      restartPolicy: Always
      containers:
      - name: server
        image: server-to-crash:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            scheme: HTTP
            port: 8080
            path: /ping
            httpHeaders:
            - name: "Accept"
              value: "text/plain"
          initialDelaySeconds: 5
          periodSeconds: 30
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3