---
apiVersion: v1
kind: Namespace
metadata:
  name: test
spec:
---
apiVersion: v1
kind: Service
metadata:
  name: nfs-service
  namespace: test
  labels:
    purpose: persistence
spec:
  selector:
    purpose: persistence
  ports:
  - port: 2049
    targetPort: 2049
    protocol: TCP
    name: tcp-2049
  - port: 111
    targetPort: 111
    protocol: UDP
    name: udp-111
  type: ClusterIP
---
apiVersion: v1
kind: Pod
metadata:
  name: nfs-server
  namespace: test
  labels:
    purpose: persistence
spec:
  containers:
  - name: nfs-server
    image: cpuguy83/nfs-server
    securityContext:
      privileged: true
    args:
    - /data