---
apiVersion: v1
kind: Pod
metadata:
  name: client-with-nfs-server
  namespace: test
  labels:
    purpose: testing-nfs-server
spec:
  containers:
  - name: client-with-nfs-server
    image: alpine:3.16
    securityContext:
      privileged: true
    volumeMounts:
    - name: nfs-volume
      mountPath: /var/nfs
    command: ["/bin/sh"]
    args: ["-c", "while true; do sleep 10s; done"]
  volumes:
  - name: nfs-volume
    persistentVolumeClaim:
      claimName: nfs-pvc