---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
  namespace: test
spec:
  capacity:
    storage: 4Gi
  volumeMode: Filesystem # The other one is block, and Filesystem is the default
  accessModes:
  - ReadWriteMany # The others are: ReadWriteOnce, ReadOnlyMany, ReadWriteMany, ReadWriteOncePod
  persistentVolumeReclaimPolicy: Retain # The others are: Retain, Delete and Recycle (deprecated)
  storageClassName: nfs
  mountOptions:
  - hard
  nfs:
    path: /mnt/nfs_share
    server: NFS_SERVER_IP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc
  namespace: test
spec:
  storageClassName: nfs
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi