---
apiVersion: v1
kind: Namespace
metadata:
  name: test
spec:
---
apiVersion: v1
kind: Service
metadata:
  name: http-readiness-probe
  namespace: test
  labels:
    app.kubernetes.io/name: http
    app.kubernetes.io/part-of: readiness
    app.kubernetes.io/component: web
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: http
    app.kubernetes.io/part-of: readiness
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-readiness-probe
  namespace: test
  labels:
    app.kubernetes.io/name: http
    app.kubernetes.io/part-of: readiness
    app.kubernetes.io/component: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: http
      app.kubernetes.io/part-of: readiness
  template:
    metadata:
      labels:
        app.kubernetes.io/name: http
        app.kubernetes.io/part-of: readiness
    spec:
      restartPolicy: Always
      containers:
      - name: http
        image: server-to-crash:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        readinessProbe:
          httpGet:
            scheme: HTTP
            port: 8080
            path: /ping
            httpHeaders:
            - name: Accept
              value: "text/plain"
          initialDelaySeconds: 5
          timeoutSeconds: 5
          periodSeconds: 15
          successThreshold: 1
          failureThreshold: 3