---
apiVersion: v1
kind: Namespace
metadata:
  name: test1
spec:
---
apiVersion: v1
kind: Namespace
metadata:
  name: test2
spec:
---
apiVersion: v1
kind: Namespace
metadata:
  name: test3
spec:
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app1
  namespace: test1
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: app1-viewer
rules:
  - apiGroups: ['']
    resources:
    - pods
    - services
    verbs:
    - get
    - list
    - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: app1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: app1-viewer
subjects:
- kind: ServiceAccount
  name: app1
  namespace: test1