---
apiVersion: v1
kind: Namespace
metadata:
  name: test1
spec:
---
apiVersion: v1
kind: Namespace
metadata:
  name: test2
spec:
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app1
  namespace: test1
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: app1-viewer
  namespace: test2
rules:
  - apiGroups: ['']
    resources:
    - pods
    - services
    verbs:
    - list
    - get
    - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: app1
  namespace: test2
roleRef: # Notice that roleRef don't use namespace! This means that a rolebinding can only reference and bind a role that is inside its own namespace.
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: app1-viewer
subjects:
- kind: ServiceAccount
  name: app1
  namespace: test1