---
apiVersion: v1
kind: Namespace
metadata:
  name: test
spec:
---
apiVersion: v1
kind: Pod
metadata:
  name: containers-sharing-pid-namespace
  namespace: test
spec:
  shareProcessNamespace: true # https://kubernetes.io/docs/tasks/configure-pod-container/share-process-namespace/
  containers:
  - name: nginx-web
    image: nginx:1.22
    imagePullPolicy: IfNotPresent
    ports:
    - name: http
      containerPort: 80
      protocol: TCP
  - name: client
    image: alpine:3.16
    imagePullPolicy: IfNotPresent
    securityContext:
      capabilities:
        add:
        - SYS_PTRACE
    tty: true
    stdin: true