---
apiVersion: v1
kind: Namespace
metadata:
  name: test
spec:
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-with-probes
  namespace: test
  labels:
    app.kubernetes.io/name: mongodb
    app.kubernetes.io/part-of: probes
    app.kubernetes.io/component: database
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: mongodb
    app.kubernetes.io/part-of: probes
  ports:
  - name: mongodb
    port: 27017
    targetPort: 27017
    protocol: TCP
---
apiVersion: v1
kind: Pod
metadata:
  name: mongodb-with-probes
  namespace: test
  labels:
    app.kubernetes.io/name: mongodb
    app.kubernetes.io/part-of: probes
    app.kubernetes.io/component: database
spec:
  restartPolicy: OnFailure
  containers:
  - name: mongodb
    image: mongo:5.0
    imagePullPolicy: IfNotPresent
    ports:
    - name: mongodb
      containerPort: 27017
      protocol: TCP
    livenessProbe:
      exec:
        command: ['mongo', '--eval', 'db.adminCommand("ping")']
      initialDelaySeconds: 10
      periodSeconds: 30
      timeoutSeconds: 5
    readinessProbe:
      exec:
        command: ['mongo', '--eval', 'db.adminCommand("ping")']
      initialDelaySeconds: 10
      periodSeconds: 30
      timeoutSeconds: 5
    env:
    - name: MONGO_INITDB_ROOT_PASSWORD
      value: "abc123."
    - name: MONGO_INITDB_ROOT_USERNAME
      value: username
